<?php

return [
    # 系统后台需要数据
    'formType' => [
        0 => ['key' => 'string', 'name' => '单行文本', 'class' => 'text', 'alter' => 'VARCHAR', 'varlong' => '250'],
        1 => ['key' => 'text', 'name' => '多行文本', 'class' => 'textarea', 'alter' => 'TEXT', 'varlong' => '250'],
        2 => ['key' => 'editor', 'name' => '编辑器', 'class' => 'textarea', 'alter' => 'TEXT', 'varlong' => '250'],
        3 => ['key' => 'htmltext', 'name' => 'HTML文本', 'class' => 'textarea', 'alter' => 'TEXT', 'varlong' => '250'],
        4 => ['key' => 'int', 'name' => ' 整数类型', 'class' => 'text', 'alter' => 'INT', 'varlong' => '11'],
        5 => ['key' => 'float', 'name' => ' 小数类型', 'class' => 'text', 'alter' => 'FLOAT', 'varlong' => '11'],
        6 => ['key' => 'datetime', 'name' => '时间类型', 'class' => 'text', 'alter' => 'INT', 'varlong' => '11'],
        7 => ['key' => 'img', 'name' => '图片附件', 'class' => 'text', 'alter' => 'VARCHAR', 'varlong' => '250'],
#       8 => ['key' => 'addon', 'name' => '文件附件', 'class' => 'text', 'alter' => 'VARCHAR', 'varlong' => '250'],
#       9 => ['key' => 'video', 'name' => '视频附件', 'class' => 'text', 'alter' => 'VARCHAR', 'varlong' => '250'],
        10 => ['key' => 'select', 'name' => '下拉框', 'class' => 'select', 'alter' => 'VARCHAR', 'varlong' => '250'],
        11 => ['key' => 'radio', 'name' => '单选框', 'class' => 'radio', 'alter' => 'VARCHAR', 'varlong' => '250'],
        12 => ['key' => 'checkbox', 'name' => '多选框', 'class' => 'checkbox', 'alter' => 'VARCHAR', 'varlong' => '250'],
        13 => ['key' => 'selectinput', 'name' => '复合选项关联输入框', 'class' => 'text', 'alter' => 'VARCHAR', 'varlong' => '250'],
        14 => ['key' => 'decimal', 'name' => '价格', 'class' => 'text', 'alter' => 'FLOAT', 'varlong' => '50'],
    ],
    #系统后台审核动作
    'action_key_list' => [
        'pass' => 'pass',
        'back' => 'back',
        'end' => 'end',
        'defer' => 'defer',
        'grant' => 'grant', //授信
        'finish' => 'finish'
    ],
    # 短信间隔时间
    'overtime' => 120,
    # 企业适用会计制度
    'system' => [
            ['id' => 1, 'name' => '企业会计准则（一般企业）'],
            ['id' => 2, 'name' => '小企业会计准则'],
            ['id' => 3, 'name' => '其他']
    ],
    # 行业类型
    'industry' => [
            ['id' => 1, 'name' => "汽车及新能源汽车"],
            ['id' => 2, 'name' => "电子信息"],
            ['id' => 3, 'name' => "生物医药"],
            ['id' => 4, 'name' => "航空装备"],
            ['id' => 5, 'name' => "食品"],
            ['id' => 6, 'name' => "纺织服装"],
            ['id' => 7, 'name' => "新材料"],
            ['id' => 8, 'name' => "机电制造"],
            ['id' => 9, 'name' => "VR/AR产业"],
            ['id' => 10, 'name' => "其他"]
    ],
    # 企业类型
    'enterprise' => [
            ['id' => 1, 'name' => '国家科技型中小企业', 'special' => false],
            ['id' => 2, 'name' => '省级科技型中小企业', 'special' => false],
            ['id' => 3, 'name' => '国家高新技术企业', 'special' => false],
            ['id' => 4, 'name' => '其他', 'special' => true]
    ],
    # 金融支持
    'supports' => [
        'fund' => [
                ['id' => 1, 'name' => '科技银行贷款'],
                ['id' => 2, 'name' => '其他银行贷款'],
                ['id' => 3, 'name' => '小贷'],
                ['id' => 4, 'name' => '保理'],
                ['id' => 5, 'name' => '融资租赁'],
                ['id' => 6, 'name' => '担保'],
                ['id' => 7, 'name' => '其他']
        ],
        'orther' => [
                ['id' => 8, 'name' => '股权融资'],
                ['id' => 9, 'name' => '挂牌上市'],
                ['id' => 10, 'name' => '并购服务'],
                ['id' => 11, 'name' => '其他']
        ]
    ],
    
    #还款方式
    'repayment_mode' =>[
        1 => '先息后本',
        2 => '等额本息',
        3 => '等额本金',
        4 => '等本等息',
        5 => '灵活还款',
        6 => '随借随还',
        7 => '一次性还本付息'
    ],

    #还款状态
    'repayment_status' => [
        1 => '按期还款',
        2 => '提前还款',
        3 => '延期还款',
        4 => '已逾期',
    ],

    #放款状态
    'loan_status' => [
        0 => '未放款',
        1 => '未全额放款',
        2 => '已全额放款',
    ],

    'mimes' => [
        'hqx'   =>  ['application/mac-binhex40', 'application/mac-binhex', 'application/x-binhex40', 'application/x-mac-binhex40'],
        'cpt'   =>  'application/mac-compactpro',
        'csv'   =>  ['text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream', 'application/vnd.ms-excel', 'application/x-csv', 'text/x-csv', 'text/csv', 'application/csv', 'application/excel', 'application/vnd.msexcel', 'text/plain'],
        'bin'   =>  ['application/macbinary', 'application/mac-binary', 'application/octet-stream', 'application/x-binary', 'application/x-macbinary'],
        'dms'   =>  'application/octet-stream',
        'lha'   =>  'application/octet-stream',
        'lzh'   =>  'application/octet-stream',
        'exe'   =>  ['application/octet-stream', 'application/x-msdownload'],
        'class' =>  'application/octet-stream',
        'psd'   =>  ['application/x-photoshop', 'image/vnd.adobe.photoshop'],
        'so'    =>  'application/octet-stream',
        'sea'   =>  'application/octet-stream',
        'dll'   =>  'application/octet-stream',
        'oda'   =>  'application/oda',
        'pdf'   =>  ['application/pdf', 'application/force-download', 'application/x-download', 'binary/octet-stream'],
        'ai'    =>  ['application/pdf', 'application/postscript'],
        'eps'   =>  'application/postscript',
        'ps'    =>  'application/postscript',
        'smi'   =>  'application/smil',
        'smil'  =>  'application/smil',
        'mif'   =>  'application/vnd.mif',
        'xls'   =>  ['application/vnd.ms-excel', 'application/msexcel', 'application/x-msexcel', 'application/x-ms-excel', 'application/x-excel', 'application/x-dos_ms_excel', 'application/xls', 'application/x-xls', 'application/excel', 'application/download', 'application/vnd.ms-office', 'application/msword'],
        'ppt'   =>  ['application/powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.ms-office', 'application/msword'],
        'pptx'  =>  ['application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/x-zip', 'application/zip'],
        'wbxml' =>  'application/wbxml',
        'wmlc'  =>  'application/wmlc',
        'dcr'   =>  'application/x-director',
        'dir'   =>  'application/x-director',
        'dxr'   =>  'application/x-director',
        'dvi'   =>  'application/x-dvi',
        'gtar'  =>  'application/x-gtar',
        'gz'    =>  'application/x-gzip',
        'gzip'  =>  'application/x-gzip',
        'php'   =>  ['application/x-httpd-php', 'application/php', 'application/x-php', 'text/php', 'text/x-php', 'application/x-httpd-php-source'],
        'php4'  =>  'application/x-httpd-php',
        'php3'  =>  'application/x-httpd-php',
        'phtml' =>  'application/x-httpd-php',
        'phps'  =>  'application/x-httpd-php-source',
        'js'    =>  ['application/x-javascript', 'text/plain'],
        'swf'   =>  'application/x-shockwave-flash',
        'sit'   =>  'application/x-stuffit',
        'tar'   =>  'application/x-tar',
        'tgz'   =>  ['application/x-tar', 'application/x-gzip-compressed'],
        'z' =>  'application/x-compress',
        'xhtml' =>  'application/xhtml+xml',
        'xht'   =>  'application/xhtml+xml',
        'zip'   =>  ['application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/s-compressed', 'multipart/x-zip'],
        'rar'   =>  ['application/x-rar', 'application/rar', 'application/x-rar-compressed'],
        'mid'   =>  'audio/midi',
        'midi'  =>  'audio/midi',
        'mpga'  =>  'audio/mpeg',
        'mp2'   =>  'audio/mpeg',
        'mp3'   =>  ['audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'],
        'aif'   =>  ['audio/x-aiff', 'audio/aiff'],
        'aiff'  =>  ['audio/x-aiff', 'audio/aiff'],
        'aifc'  =>  'audio/x-aiff',
        'ram'   =>  'audio/x-pn-realaudio',
        'rm'    =>  'audio/x-pn-realaudio',
        'rpm'   =>  'audio/x-pn-realaudio-plugin',
        'ra'    =>  'audio/x-realaudio',
        'rv'    =>  'video/vnd.rn-realvideo',
        'wav'   =>  ['audio/x-wav', 'audio/wave', 'audio/wav'],
        'bmp'   =>  ['image/bmp', 'image/x-bmp', 'image/x-bitmap', 'image/x-xbitmap', 'image/x-win-bitmap', 'image/x-windows-bmp', 'image/ms-bmp', 'image/x-ms-bmp', 'application/bmp', 'application/x-bmp', 'application/x-win-bitmap'],
        'gif'   =>  'image/gif',
        'jpeg'  =>  ['image/jpeg', 'image/pjpeg'],
        'jpg'   =>  ['image/jpeg', 'image/pjpeg'],
        'jpe'   =>  ['image/jpeg', 'image/pjpeg'],
        'jp2'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'j2k'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'jpf'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'jpg2'  =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'jpx'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'jpm'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'mj2'   =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'mjp2'  =>  ['image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'],
        'png'   =>  ['image/png',  'image/x-png'],
        'tiff'  =>  'image/tiff',
        'tif'   =>  'image/tiff',
        'css'   =>  ['text/css', 'text/plain'],
        'html'  =>  ['text/html', 'text/plain'],
        'htm'   =>  ['text/html', 'text/plain'],
        'shtml' =>  ['text/html', 'text/plain'],
        'txt'   =>  'text/plain',
        'text'  =>  'text/plain',
        'log'   =>  ['text/plain', 'text/x-log'],
        'rtx'   =>  'text/richtext',
        'rtf'   =>  'text/rtf',
        'xml'   =>  ['application/xml', 'text/xml', 'text/plain'],
        'xsl'   =>  ['application/xml', 'text/xsl', 'text/xml'],
        'mpeg'  =>  'video/mpeg',
        'mpg'   =>  'video/mpeg',
        'mpe'   =>  'video/mpeg',
        'qt'    =>  'video/quicktime',
        'mov'   =>  'video/quicktime',
        'avi'   =>  ['video/x-msvideo', 'video/msvideo', 'video/avi', 'application/x-troff-msvideo'],
        'movie' =>  'video/x-sgi-movie',
        'doc'   =>  ['application/msword', 'application/vnd.ms-office'],
        'docx'  =>  ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword', 'application/x-zip'],
        'dot'   =>  ['application/msword', 'application/vnd.ms-office'],
        'dotx'  =>  ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword'],
        'xlsx'  =>  ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip', 'application/vnd.ms-excel', 'application/msword', 'application/x-zip'],
        'word'  =>  ['application/msword', 'application/octet-stream'],
        'xl'    =>  'application/excel',
        'eml'   =>  'message/rfc822',
        'json'  =>  ['application/json', 'text/json'],
        'pem'   =>  ['application/x-x509-user-cert', 'application/x-pem-file', 'application/octet-stream'],
        'p10'   =>  ['application/x-pkcs10', 'application/pkcs10'],
        'p12'   =>  'application/x-pkcs12',
        'p7a'   =>  'application/x-pkcs7-signature',
        'p7c'   =>  ['application/pkcs7-mime', 'application/x-pkcs7-mime'],
        'p7m'   =>  ['application/pkcs7-mime', 'application/x-pkcs7-mime'],
        'p7r'   =>  'application/x-pkcs7-certreqresp',
        'p7s'   =>  'application/pkcs7-signature',
        'crt'   =>  ['application/x-x509-ca-cert', 'application/x-x509-user-cert', 'application/pkix-cert'],
        'crl'   =>  ['application/pkix-crl', 'application/pkcs-crl'],
        'der'   =>  'application/x-x509-ca-cert',
        'kdb'   =>  'application/octet-stream',
        'pgp'   =>  'application/pgp',
        'gpg'   =>  'application/gpg-keys',
        'sst'   =>  'application/octet-stream',
        'csr'   =>  'application/octet-stream',
        'rsa'   =>  'application/x-pkcs7',
        'cer'   =>  ['application/pkix-cert', 'application/x-x509-ca-cert'],
        '3g2'   =>  'video/3gpp2',
        '3gp'   =>  ['video/3gp', 'video/3gpp'],
        'mp4'   =>  'video/mp4',
        'm4a'   =>  'audio/x-m4a',
        'f4v'   =>  ['video/mp4', 'video/x-f4v'],
        'flv'   =>  'video/x-flv',
        'webm'  =>  'video/webm',
        'aac'   =>  'audio/x-acc',
        'm4u'   =>  'application/vnd.mpegurl',
        'm3u'   =>  'text/plain',
        'xspf'  =>  'application/xspf+xml',
        'vlc'   =>  'application/videolan',
        'wmv'   =>  ['video/x-ms-wmv', 'video/x-ms-asf'],
        'au'    =>  'audio/x-au',
        'ac3'   =>  'audio/ac3',
        'flac'  =>  'audio/x-flac',
        'ogg'   =>  ['audio/ogg', 'video/ogg', 'application/ogg'],
        'kmz'   =>  ['application/vnd.google-earth.kmz', 'application/zip', 'application/x-zip'],
        'kml'   =>  ['application/vnd.google-earth.kml+xml', 'application/xml', 'text/xml'],
        'ics'   =>  'text/calendar',
        'ical'  =>  'text/calendar',
        'zsh'   =>  'text/x-scriptzsh',
        '7z'    =>  ['application/x-7z-compressed', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip'],
        '7zip'  =>  ['application/x-7z-compressed', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip'],
        'cdr'   =>  ['application/cdr', 'application/coreldraw', 'application/x-cdr', 'application/x-coreldraw', 'image/cdr', 'image/x-cdr', 'zz-application/zz-winassoc-cdr'],
        'wma'   =>  ['audio/x-ms-wma', 'video/x-ms-asf'],
        'jar'   =>  ['application/java-archive', 'application/x-java-application', 'application/x-jar', 'application/x-compressed'],
        'svg'   =>  ['image/svg+xml', 'application/xml', 'text/xml'],
        'vcf'   =>  'text/x-vcard',
        'srt'   =>  ['text/srt', 'text/plain'],
        'vtt'   =>  ['text/vtt', 'text/plain'],
        'ico'   =>  ['image/x-icon', 'image/x-ico', 'image/vnd.microsoft.icon'],
        'odc'   =>  'application/vnd.oasis.opendocument.chart',
        'otc'   =>  'application/vnd.oasis.opendocument.chart-template',
        'odf'   =>  'application/vnd.oasis.opendocument.formula',
        'otf'   =>  'application/vnd.oasis.opendocument.formula-template',
        'odg'   =>  'application/vnd.oasis.opendocument.graphics',
        'otg'   =>  'application/vnd.oasis.opendocument.graphics-template',
        'odi'   =>  'application/vnd.oasis.opendocument.image',
        'oti'   =>  'application/vnd.oasis.opendocument.image-template',
        'odp'   =>  'application/vnd.oasis.opendocument.presentation',
        'otp'   =>  'application/vnd.oasis.opendocument.presentation-template',
        'ods'   =>  'application/vnd.oasis.opendocument.spreadsheet',
        'ots'   =>  'application/vnd.oasis.opendocument.spreadsheet-template',
        'odt'   =>  'application/vnd.oasis.opendocument.text',
        'odm'   =>  'application/vnd.oasis.opendocument.text-master',
        'ott'   =>  'application/vnd.oasis.opendocument.text-template',
        'oth'   =>  'application/vnd.oasis.opendocument.text-web'
    ]                             
];
